version: '3'

services:
  database: 
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: senhasecreta
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

