CREATE TABLE IF NOT EXISTS addresses (
  id SERIAL NOT NULL PRIMARY KEY,
  city VARCHAR(100) NOT NULL,
  street VARCHAR(200) NOT NULL,
  number VARCHAR(5) NOT NULL,
  state VARCHAR(3) NOT NULL,
  neighborhood VARCHAR(40) NOT NULL
) 

--ROLLBACK 
DROP TABLE IF EXISTS addresses CASCADE
