CREATE TABLE IF NOT EXISTS logs_io_vehicles (
  id SERIAL NOT NULL,
  entry_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  departure_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  id_vehicle INTEGER NOT NULL,
  FOREIGN KEY(id_vehicle) REFERENCES vehicles(id)
)

--ROLLBACK
DROP TABLE IF EXISTS logs_io_vehicles CASCADE
